name: Trading Bot

on:
  push:   # This job will run every time a push is made to the repository
  schedule:
    # This cron job runs every hour, you can modify it as needed
    - cron: '30 10 * * *'

jobs:
  execute-trading-script:
    # The job will run on the latest Ubuntu virtual environment
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      # This step checks out the repository where the code is located
      uses: actions/checkout@v2

    - name: Set up Python environment
      # Set up the correct Python version for your script
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      # Install Python packages needed for your trading bot and other APIs
      run: |
        python -m pip install --upgrade pip
        pip install alpaca-trade-api==1.4.3
        pip install python-dotenv==0.19.2
        pip install openai==0.27.0

    - name: Run trading script
      # Run the trading script that contains your trading logic
      run: python tradingggggg.py
      env:
        BASE_URL: ${{secrets.BASE_URL}}
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY}}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY}}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
